# standalone Zookeeper for testing purposes
- name: Install Zookeeper Base
  yum:
    name: zookeeper
    state: latest

- name: Install Zookeeper Server as standalone (single node)
  yum:
    name: zookeeper-server
    state: latest

- name: Config directories
  file:
    path: /var/lib/zookeeper
    state: directory
    owner: zoopkeeper
    recurse: yes
    mode: 0755

- name: Initialise Zookeeper
  command: service zookeeper-server init

- name: Start Zookeeper
  service:
    name: zookeeper-server
    state: started
