- name: Install Data Node packages
  yum: name={{ item }} state=latest
  with_items:
    - hadoop-yarn-nodemanager
    - hadoop-hdfs-datanode
    - hadoop-mapreduce

- name: Create Data directories
  file:
    dest: "{{ item }}"
    owner: hdfs
    group: hdfs
    recurse: yes
    state: directory
    mode: 0700
  with_items:
     - "{{ dfs_datanode_data_dir.replace('file://', '').split(',') }}"

- name: Create Resource Manager Data directories
  file:
    dest: "{{ item }}"
    owner: yarn
    group: yarn
    state: directory
    recurse: yes
    mode: 0755
  with_items:
    -  "{{ yarn_nodemanager_local_dirs.replace('file://', '').split(',') }}"
    -  "{{ yarn_nodemanager_log_dirs.replace('file://', '').split(',') }}"

- name: Start DataNode
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - hadoop-hdfs-datanode
    - hadoop-yarn-nodemanager
