---
- name: Instance Running
  hosts: localhost
  gather_facts: false
  vars:
    key_name: ashley-rdp-key
    instance_type: t2.micro
    image: ami-9c363cf8
    group: default
    vpc_subnet_id: subnet-2bdd3050
  tasks:
    - name: Launch instance
      ec2:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        group: "{{ group }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        wait: yes
        count: 1
        assign_public_ip: yes
        region: eu-west-2
        instance_tags:
          Name: test
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"
