- local_action:
    module: ec2
    region: eu-west-2
    instance_tags:
        Name: cloudera_cluster_master
    state: restarted

- local_action:
    module: ec2
    region: eu-west-2
    instance_tags:
        Name: cloudera_cluster_slave
    state: restarted


- name: Wait for SSH
  wait_for:
    host: "{{ item }}"
    port: 22
    delay: 10
    timeout: 320
    state: started
  with_items: "{{ groups['launched'] }}"
